name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          # "brands" requires the integration to be merged into
          # home-assistant/brands; ignore until that PR lands.
          ignore: brands

  validate-hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
